### ISSUE TITLE
No way to clear a Skill assignment if accidentally selected

### ISSUE THREAD

**Issue by jrwarwick** [retroredge/showdown-troop-builder#1]
The best you can do is reduce to d4. Need a special control, per-skill, to remove the skill assignment.

**Comment by retroredge** [comment]
Hi Justin

That would be a good feature. I'll see if I can find time to add it next
week.

Thank you for taking the to time to give me feedback.

Regards

Nick

**Comment by jrwarwick** [comment]
You are most welcome, Nick. And thank you for making and sharing this really cool application! Have you told the PegInc guys about this? I distinctly remember reading somewhere on the site or in the official PDF that they want to publish a web app "eventually". This thing is perfect. I really like your tech choices too.
Sincerely,
- Justin

**Comment by retroredge** [comment]
Hi. 

I haven't told PegInc about it as they don't seem to be actively supporting their free 'Showdown' tactical skirmish game which the troop builder is designed for. It also needs a far better print feature that can output index card sized PDFs with all the info neatly laid out but this is a large task.

Glad you like it. I'll take a look at your pull requests when I get back from holiday and thank you for contributing. 

Nick

**Comment by schmendrick** [comment]
i think its not only the skills if you accidently select them, its the same with the stats.

easy fix: add an own entry on top of every list with the text [None] or [Empty] that will then be ignored on the printout and "0" for the cost value.

or:
add "Clear" buttons in every panel-primary (and maybe a "Clear" on bottom for clearing everything

apart from that: thank you for that tool.

> I haven't told PegInc about it as they don't seem to be actively supporting their free 'Showdown' tactical skirmish game which the troop builder is designed for. It also needs a far better print feature that can output index card sized PDFs with all the info neatly laid out but this is a large task.

BTW: i once already talked with Shane Hensley when i wrote a tool for automating a fantasy character generation book for SW that they had (but the book is not sold anymore because it didnt meet their quality standards). when i talked with him it was more than 2 years ago, but they are actually quite interested in such things, especially if its online.

**Comment by jrwarwick** [comment]
@schmendrick, I think your UI changes sound like they would be good approaches. However, I suggest that unlike skills, attributes should not be "clear-able". Although the ShowDown document does not explicitly state it, page 5 does say "Each Trait is rated from a d4 to a
d12, with a d6 being the human average." I seem to recall that in Savage Worlds proper, d4 is the general minimum unless there is some extraordinary circumstance (tiny, tiny creature or magical effects). 

So I would say we should look at your suggestions for skills, but it would appropriate to default all attributes to d6 and not permit them to be cleared.

Thanks for the note on Mr. Hensley's interest. That is encouraging. Perhaps once this project gets to the state of "1.0-worthiness" we could see if Nick would be interested in approaching Mr. Hensley. Maybe it would communicate customer interest and spark some vendor interest in the product again.

**Comment by retroredge** [comment]
@schmendrick thank you for you comments on the troop builder app. Stats are treated differently to skills in the Showdown and Savage Worlds rules. You can have no skill rating in something which means it default to d4/2 IIRC but for stats the minimum is d4.

I'd like to keep the UI as simple as possible and therefore I think the best thing is that I add a button to allow the skill to be cleared.

@Justin, I like the idea of setting the default stat to d6.

**Comment by schmendrick** [comment]
uh oh... i just realize that i actually meant nearly everything else BUT stats:
i am sorry if i have caused confusion!

to be more precise:
the issue i ACTUALLY meant is:

a) i open the builder
b) i enter my things under Info
-> if i make a mistake i can use backspace => FINE
c) i select my Stats for Ag, Sm, Sp, Str, Vig
->if i make a mistake, i can reclick => FINE
d) i select my desired Skills (Arcane, Shooting, Fighting)
-> if i by mistake click on Driving, i cannot deselect it although the rules allow it as was pointed out => (PROBLEM)
e) i choose my edges; 
-> if after choosing edges i realize i actually dont want ANY edge then i cannot deselect => PROBLEM
f) same goes for all following listboxes, namely "Special Abilities", "Misc Abilities", "Armor" and the weapons
-> if after choosing i realize i actually dont want ANY, then i cannot deselect => PROBLEM

so suggested solution:

d)
I agree with what you said:

> I'd like to keep the UI as simple as possible and therefore I think the best thing is that I add a button to allow the skill to be cleared.

e) & f)
Add a button to clear any selection of that listbox

**Comment by retroredge** [comment]
@schmendrick Hi. Regarding point e) in your list. You can deselect any item in those lists by clicking it again. That works for me on Chrome / OSX.

Regarding point d) I agree, it definitely needs a way to clear the selection :)

**Comment by schmendrick** [comment]
that is strange. if i click an item again, it does not deselect. i am using 
Google Chrome, 54.0.2840.99

maybe we are not talking about the same thing?

you can find my steps attached including description. 

[deselect-problem.zip](https://github.com/retroredge/showdown-troop-builder/files/600112/deselect-problem.zip)

**Comment by schmendrick** [comment]
@retroredge 
i just realize you said you use OSX; probably chrome will not open the MHT that I attached out of the box. however you should be able to view it
=>
https://www.techwalla.com/articles/how-to-open-mht-documents-on-a-mac

**Comment by retroredge** [comment]
Sorry I should have said select the item whilst holding down the command
key ('cmd') to deselect it.

Nick

**Comment by schmendrick** [comment]
clicking CTRL in windows does the trick. thanks for the assist

**Comment by jrwarwick** [comment]
There is now a special "x" radio button that clears off / deselects the skill and then also unchecks itself.
